### ISSUE TITLE
[IPH CTRITH] Change in visit scheduling

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/IPH-CTRITH#37]
Ticket reference:
https://avni.freshdesk.com/a/tickets/2882

**Organizations:**
UAT - IPH CTRITH UAT
Prod - CTRITH IPH

**Tasks:**
Change visit scheduling for the second visit for following forms:
1. Record Mother Anthropometry encounter
There are visits happening immediately after enrolment and then afterwards 3 months, 6 months, 1 year and 2 year from enrollment. 
- [x] Keep the first visit as it is. Change scheduling for remaining to do it from the data of Delivery, and not based on enrollment. Date of delivery is captured in the Delivery form.
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=1782789233
2. Encounter - "Record Child Anthropometry details" 
There are visits happening immediately after enrolment and then afterwards 3 months, 6 months, 1 year and 2 year from enrollment. 
- [x] Keep the first visit as it is. Change scheduling for remaining to do it from the data of birth recorded for Child in the registration, and not based on enrollment. 
https://docs.google.com/spreadsheets/d/1GX2ypTkZQnzUHMFuE8haULUZ61PPhyB2PU6HFVdZwqg/edit#gid=1782789233

**Comment by BEULAHEVANJALIN** [comment]
Blocked! Issue with bundle upload

**Comment by BEULAHEVANJALIN** [comment]
Blocked! The app crashes when I try to enroll an individual in the mother program. 


![image.png](https://images.zenhubusercontent.com/6391ce979fce9d1191f3aaac/f4bb210f-a32a-400b-b21e-58804873cb71)

**Comment by BEULAHEVANJALIN** [comment]
Oh hold! (BA needs to clarify requirements with the client)

**Comment by Dinesh2019** [comment]
- [ ] If we have exited the individual from the mother program and if I complete the visit the next visit should not be scheduled as per the requirements 3,6,1 and 2 years but it keeps on scheduling for now we are ignoring this scenario.

Test Scenario:
1. Create the individual and enroll in the mother program and validate the visit scheduled as per the delivery date
2. Edited the delivery date after completing the visit and checked the  visit is scheduled as per the new delivery 
date
3. Voided the individual and tried to complete the visit but as expected the error shows up we cannot complete the visit for the voided individual
